name: TryAppImage

on:
  push:
    branches: [ maser ] #note the typo
  pull_request:
    branches: [ maser ]

jobs:
  build-appimage:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2 #1
      - uses: actions/setup-python@v3 #2
        with:
          python-version: '3.8.10'

      - name: install dependencies #3
        run: |
          sudo apt update
          sudo apt install build-essential git pkg-config python3-dev python3-venv libgirepository1.0-dev libcairo2-dev gir1.2-webkit2-4.0 libcanberra-gtk3-module
          python -m pip install briefcase        
      - name: Build AppImage #4
        run: |
          briefcase build
          briefcase package linux appimage
      - uses: actions/upload-artifact@v2 #5
        with:
          name: AppImage 
          path: "./dist/*.AppImage*"

          
          

          
