name: TryInstallersMultiOS

on:
  #push:
  #  branches: [ maser ] #note the typo
  #pull_request:
  #  branches: [ maser ]
  workflow_dispatch:
      inputs: #when run, ask user to input release tag
        reltag:
          description: "tag for release, eg v1.0.0"
          required: true
          default: "latest"       
 
  

jobs:
  build-installersmulti:
    runs-on: ${{ matrix.os }}

    strategy:
          matrix:
                os: [ubuntu-20.04, windows-2019]
                
    env: 
      TAGNAME: ${{ inputs.reltag }} #ask user for release tag

    steps:
      - uses: actions/checkout@v2 #1
      - uses: actions/setup-python@v3 #2
        with:
          python-version: '3.8.10'
      # if else is a bit tricky on actions if you are using 'if: runner.os == ' notation
      # so let me break it in two parts
      # interestingly , no commands are exclusive for windows, so out code does not have 
      #  the if stetement if: runner.os == 'Windows'
      - name: install dependencies Linux  
        if: runner.os == 'Linux' 
        run: |          
              sudo apt update
              sudo apt install -yq build-essential git pkg-config python3-dev python3-venv \
              libgirepository1.0-dev libcairo2-dev \
              gir1.2-webkit2-4.0 libcanberra-gtk3-module libgl1 libglib2.0-0              
              
      - name: install briefcase                  # All OSs  will run this command      
        run: |
             python -m pip install briefcase

      - name: Perform briefcase build  #4         #  Al OSs will run this command
        run: 
          briefcase build                         # All  OSs
      - name: Briefcase package linux   
        if: runner.os == 'Linux' 
        run: 
            briefcase package linux appimage      # creates appimage file 
                     
      - name: Briefcase package system           #  All OSs    
        run:             
            briefcase package                     # creates .deb file on ubuntu, .msi on windows  
               

      - uses: actions/upload-artifact@v2 #5
        with:
          name: linuxartifacts 
          path: "./dist/" # directory

      - uses: marvinpinto/action-automatic-releases@latest # {{xyz}}varaibles not available in uses
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"          
          automatic_release_tag: "${{ inputs.reltag }}" 
          prerelease: true
          title: "Build ${{ github.event.inputs.reltag }}" #same as inputs.reltag 
          files: |            
            ./dist/*
            


          
          

          
